#
# Run this file using
#
# $ docker-compose up processor
#
version: "3.9"
services:
  pre-commit:
    build:
      context: .
      dockerfile: tests/Dockerfile.pre-commit
    working_dir: /code
    volumes:
    - .:/code
  super-linter:
    image: github/super-linter
    environment:
    - RUN_LOCAL=true
    - VALIDATE_MARKDOWN=false
    - VALIDATE_PYTHON_ISORT=false
    - VALIDATE_XML=false
    - VALIDATE_NATURAL_LANGUAGE=false
    - IGNORE_GITIGNORED_FILES=true
    volumes:
    - .:/tmp/lint/
    - ./tox.ini:/action/lib/.automation/.flake8
  # This container will run successfully
  # only if all dependencies return no errors.
  test:
    image: busybox
    depends_on:
      pre-commit:
        condition: service_completed_successfully
      super-linter:
        condition: service_completed_successfully
  virtuoso:
    # user: "1000:1000"
    image: docker.io/openlink/virtuoso-opensource-7:7.2.12-alpine
    ports:
      - "18890:8890/tcp"
    environment:
      - VIRTUOSO_INI_FILE=/virtuoso.ini
      - DBA_PASSWORD=dba
    volumes:
      - .:/code
      - ./data:/database
      - ./vocabularies:/initdb.d/
      - ./sparql/virtuoso.ini:/virtuoso.ini
